#include "module_build.h"
#include "project.h"
#include "../core/json.h"
#include "../core/log.h"
#include "../core/paths.h"
#include "../core/process.h"
#include <fstream>
#include <sstream>

namespace ae {

namespace {

// Forward slashes for CMake (backslashes are escape characters there).
std::string cmakePath(std::string p) {
    for (char& c : p)
        if (c == '\\') c = '/';
    return p;
}

struct SdkPaths {
    std::string include, lib;
};

bool readSdkPaths(SdkPaths& out, const std::function<void(const std::string&)>& onLine) {
    std::string manifest = joinPath(engineBinDir(), "engine.json");
    std::ifstream f(manifest, std::ios::binary);
    if (!f) {
        onLine("[Module] engine manifest not found: " + manifest);
        return false;
    }
    std::ostringstream ss;
    ss << f.rdbuf();
    std::string text = ss.str();
    JsonValue doc;
    if (!jsonParse(text.c_str(), text.size(), doc)) {
        onLine("[Module] malformed engine.json: " + manifest);
        return false;
    }
    if (const std::string* s = doc.string("sdkInclude")) out.include = *s;
    if (const std::string* s = doc.string("sdkLib")) out.lib = *s;
    if (out.include.empty() || out.lib.empty()) {
        onLine("[Module] engine.json lacks sdkInclude/sdkLib");
        return false;
    }
    return true;
}

} // namespace

bool buildModuleAt(const std::string& sourceDir, const std::string& moduleName,
                   const std::string& binariesDir, const std::string& intermediateDir,
                   const std::string& config,
                   const std::function<void(const std::string&)>& onLine) {
    SdkPaths sdk;
    if (!readSdkPaths(sdk, onLine)) return false;
    if (!isDirectory(sourceDir)) {
        onLine("[Module] no source directory: " + sourceDir);
        return false;
    }

    // Regenerate the module's build script every compile so new .cpp files and
    // engine SDK moves are always picked up.
    {
        std::ostringstream o;
        o << "# Generated by Aether Engine — regenerated on every Compile; do not edit.\n"
          << "cmake_minimum_required(VERSION 3.16)\n"
          << "project(" << moduleName << " CXX)\n"
          << "set(CMAKE_CXX_STANDARD 17)\n"
          << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n"
          << "file(GLOB_RECURSE AE_SCRIPT_SOURCES CONFIGURE_DEPENDS\n"
          << "     ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)\n"
          << "add_library(" << moduleName << " SHARED ${AE_SCRIPT_SOURCES})\n"
          << "target_include_directories(" << moduleName << " PRIVATE \""
          << cmakePath(sdk.include) << "\")\n"
          << "target_link_libraries(" << moduleName << " PRIVATE \""
          << cmakePath(sdk.lib) << "/AetherCore.lib\")\n"
          << "if(MSVC)\n"
          << "    target_compile_options(" << moduleName << " PRIVATE /W3 /permissive- /MP)\n"
          << "endif()\n"
          << "foreach(cfg RELEASE DEBUG RELWITHDEBINFO MINSIZEREL)\n"
          << "    set_target_properties(" << moduleName << " PROPERTIES\n"
          << "        RUNTIME_OUTPUT_DIRECTORY_${cfg} \"" << cmakePath(binariesDir) << "\")\n"
          << "endforeach()\n";
        std::ofstream f(joinPath(sourceDir, "CMakeLists.txt"), std::ios::binary);
        if (!f) {
            onLine("[Module] cannot write " + joinPath(sourceDir, "CMakeLists.txt"));
            return false;
        }
        f << o.str();
    }

    // Configure (cheap no-op when already configured), then build.
    std::string configure = "cmake -S \"" + sourceDir + "\" -B \"" + intermediateDir + "\"";
    onLine("[Module] " + configure);
    int rc = runProcessCaptured(configure, sourceDir, onLine);
    if (rc == -1) {
        onLine("[Module] cannot run cmake — is CMake installed and on PATH?");
        return false;
    }
    if (rc != 0) {
        onLine("[Module] cmake configure failed (exit " + std::to_string(rc) + ")");
        return false;
    }

    std::string build = "cmake --build \"" + intermediateDir + "\" --config " + config;
    onLine("[Module] " + build);
    rc = runProcessCaptured(build, sourceDir, onLine);
    if (rc != 0) {
        onLine("[Module] build failed (exit " + std::to_string(rc) + ")");
        return false;
    }
    onLine("[Module] built " + joinPath(binariesDir, moduleName + ".dll"));
    return true;
}

bool buildGameModule(const Project& project, const std::string& config,
                     const std::function<void(const std::string&)>& onLine) {
    if (!project.hasModule()) {
        onLine("[Module] project declares no native module");
        return false;
    }
    return buildModuleAt(joinPath(project.root, project.sourceDir), project.moduleName,
                         joinPath(project.root, "Binaries"),
                         joinPath(project.root, "Intermediate\\ModuleBuild"), config, onLine);
}

} // namespace ae
